### PR TITLE
feat: add team Super Sonic tech radar (2021-Q1)

### PR DESCRIPTION
**Pull request by kewah**
Added the entries for team Super Sonic. 

The layout is broken because the names are too long when we include the team's name. We can live with it until we find another way of having a radar for each team. 

We need to investigate if we can increase the number of slices in the radar—to have one per teams.

### CODE REVIEW

**Comment by kewah** [comment]
@petrenkotino I removed Google Analytics. Let me know if that's our account and if we should keep it.

**Comment by felixrosenvik** [comment]
Wild stuff! Should data-service be in here somewhere? (I can't remember what technology is backing DS though)

**Comment by kewah** [comment]
@felixrosenvik Good point 👍  I put it under the "Azure" umbrella, but we could be more granular like for AWS.

**Comment by sundeqvist** [comment]
> Wild stuff! Should data-service be in here somewhere? (I can't remember what technology is backing DS though)

truly wild

**Review by lndbrg — APPROVED** [review]

**Pull request merged**
